export default {
  // home
  CHANGE_COLLECTION_COUNT: 'CHANGE_COLLECTION_COUNT',
  CHANGE_IS_MODAL_VISIBLE: 'CHANGE_IS_MODAL_VISIBLE',
  CHANGE_IS_SUB_MODAL_VISIBLE: 'CHANGE_IS_SUB_MODAL_VISIBLE',
  CHANGE_COLLECTION_LIST: 'CHANGE_COLLECTION_LIST',
  CHANGE_MODAL_TYPE: 'CHANGE_MODAL_TYPE',
  CHANGE_SHOW_LOADING: 'CHANGE_SHOW_LOADING',

  // Clips page
  CHANGE_COLLECTION_LIST_CLIP: 'CHANGE_COLLECTION_LIST_CLIP',
  CHANGE_CLIP_LIST: 'CHANGE_CLIP_LIST',
  CHANGE_IS_MODAL_VISIBLE_CLIP: 'CHANGE_IS_MODAL_VISIBLE_CLIP',
  CHANGE_SELECTED_ITEM: 'CHANGE_SELECTED_ITEM',
  CHANGE_FAB_CLICKED: 'CHANGE_FAB_CLICKED',
  CHANGE_MODAL_TYPE_CLIP: 'CHANGE_MODAL_TYPE_CLIP',
  CHANGE_IS_SUB_MODAL_VISIBLE_CLIP: 'CHANGE_IS_SUB_MODAL_VISIBLE_CLIP',
  CHANGE_EDIT_VALUE: 'CHANGE_EDIT_VALUE',
  CHANGE_EDIT_COLLECTION_VALUE: 'CHANGE_EDIT_COLLECTION_VALUE',
  CHANGE_SHOW_LOADING_CLIP: 'CHANGE_SHOW_LOADING_CLIP',
};
