export default {
  APP_NAME: 'Clippy',

  CREATE_COLLECTION: 'Create a collection',
  CREATE_CLIP: 'Create a clip',
  COLLECTION_NAME: 'Collection name',
  COLLECTION: 'Collection',
  URL: 'URL',
  CREATE: 'Create',
  CANCEL: 'Cancel',
  UPDATE_CLIP : 'Update Clip',
  UPDATE : 'Update',
  OPEN_IN_BROWSER:'Open in browser',
  MARK_AS_READ:'Mark as read/unread',
  EDIT:'Edit',
  DELETE:'Delete',
  ALERT:'Alert',
  DELETE_ALERT:'Are you sure you want to delete the clip ?',
  OK:'OK',
  DELETE_COLLECTION_ALERT:'Are you sure you want to delete the collection ?',
  ERROR_1:'Sorry, something went wrong.',
  TRY_AGAIN:'Please try again later.',
  READ :'Read',
  NO_CLIPS:'No clips!',
};
